# Usa una imagen base de Node.js compatible
FROM node:18

# Establece el directorio de trabajo
WORKDIR /var/www/html

# Copia los archivos del proyecto
COPY . .

# Instala las dependencias
RUN npm install

# Expone el puerto que utiliza Vite
EXPOSE 5173

# Comando para iniciar Vite
CMD ["npm", "run", "dev"]